/* =============================================================
 * SHELLY OG — נתוני דמו (Mock Data)
 * הנתונים כאן מאפשרים לסקור את המוצר מיד, בלי חיבורים חיצוניים.
 * המבנה תואם 1:1 ל-types.ts ומוכן להתחלף בנתונים אמיתיים
 * מ-Google Sheets / DB דרך adapter-ים ב-lib/google.
 * ============================================================= */

import type {
  Idea,
  Trend,
  Project,
  ContentLibraryItem,
  WeeklyReview,
  PublishedContentItem,
  Opportunity,
  NextAction,
  NewsHeadline,
  DailyPost,
} from "./types";

/* ---------- פרויקטים ---------- */
export const mockProjects: Project[] = [
  {
    id: "proj_lecture_ai_brands",
    name: "הרצאה: AI שמוכר — איך מותגים מייצרים תוכן ב-2026",
    type: "lecture",
    status: "active",
    deadline: "2026-06-04",
    relatedDriveFolder: "Drive › הרצאות › AI שמוכר",
    relatedDocs: [
      { name: "מצגת — טיוטה 3", link: "#docs/ai-sells-deck" },
      { name: "סקריפט פתיחה", link: "#docs/ai-sells-script" },
    ],
    relatedEmails: [
      { subject: "אישור הרצאה — כנס שיווק דיגיטלי", from: "הפקה — Marketing Summit" },
    ],
    relatedCalendarEvents: [{ title: "הרצאה בכנס שיווק דיגיטלי", date: "2026-06-04" }],
    relatedIdeas: ["idea_carousel_ai_workflow", "idea_reels_prompt_fail"],
    summary:
      "הרצאת בוקר ל-300 אנשי שיווק. הסיפור המרכזי: AI הוא לא כלי, הוא שותף קריאייטיב. צריך 3 דמואים חיים ו-2 קייסים ישראליים.",
    missingItems: ["דמו חי שלישי", "קייס ישראלי שני", "שקופית סיכום עם CTA"],
    nextStep: "להקליט דמו חי שלישי ולשבץ במצגת — עבודה עמוקה של שעה.",
    contentOpportunities: [
      "קרוסלת לינקדאין: '5 דברים שאמרתי בהרצאה'",
      "רילס מאחורי הקלעים של ההכנה",
      "פוסט סמכות: מה מותגים עדיין טועים ב-AI",
    ],
    progress: 68,
    createdAt: "2026-04-28T09:00:00Z",
  },
  {
    id: "proj_series_prompt_school",
    name: "סדרת תוכן: בית הספר לפרומפטים",
    type: "content-series",
    status: "active",
    deadline: "2026-07-15",
    relatedDriveFolder: "Drive › סדרות › Prompt School",
    relatedDocs: [{ name: "מאגר פרומפטים — Sheet", link: "#sheets/prompt-bank" }],
    relatedEmails: [],
    relatedCalendarEvents: [{ title: "צילום פרק 2", date: "2026-05-26" }],
    relatedIdeas: ["idea_reels_prompt_fail", "idea_prompt_layers"],
    summary:
      "סדרת רילס שבועית שמלמדת פרומפטינג בגובה העיניים. פרק 1 עלה והביא שמירות גבוהות. הקהל מבקש המשך.",
    missingItems: ["תסריט פרק 3", "אינטרו ויזואלי אחיד"],
    nextStep: "לכתוב תסריט לפרק 3 על 'שכבות בפרומפט' — 30 דקות.",
    contentOpportunities: [
      "להפוך כל פרק לקרוסלה מקבילה",
      "ניוזלטר חודשי: 'הפרומפט של החודש'",
    ],
    progress: 40,
    createdAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "proj_client_fintech",
    name: "לקוח: ליווי AI לצוות תוכן בפינטק",
    type: "client",
    status: "review",
    deadline: "2026-05-30",
    relatedDriveFolder: "Drive › לקוחות › Fintech Co",
    relatedDocs: [{ name: "מסמך אסטרטגיה", link: "#docs/fintech-strategy" }],
    relatedEmails: [
      { subject: "פולואפ — סבב הערות על המתווה", from: "מנהלת תוכן — Fintech Co" },
    ],
    relatedCalendarEvents: [{ title: "סשן סיכום עם הלקוח", date: "2026-05-29" }],
    relatedIdeas: [],
    summary:
      "ליווי בן 6 שבועות לצוות תוכן. בנינו workflow מבוסס AI. נשאר סבב הערות אחרון לפני מסירה.",
    missingItems: ["תשובה לסבב ההערות האחרון"],
    nextStep: "להגיב למייל הפולואפ של מנהלת התוכן — 15 דקות.",
    contentOpportunities: [
      "קייס סטדי אנונימי לפוסט סמכות בלינקדאין",
      "זווית להרצאה: איך בונים workflow תוכן בארגון",
    ],
    progress: 88,
    createdAt: "2026-04-14T09:00:00Z",
  },
  {
    id: "proj_brand_personal",
    name: "מותג אישי: ביסוס מיצוב 'הקול של AI בעברית'",
    type: "personal-brand",
    status: "active",
    deadline: null,
    relatedDriveFolder: "Drive › מותג אישי",
    relatedDocs: [{ name: "מסמך מיצוב ונרטיב", link: "#docs/positioning" }],
    relatedEmails: [],
    relatedCalendarEvents: [],
    relatedIdeas: ["idea_linkedin_authority", "idea_personal_story"],
    summary:
      "פרויקט-על מתמשך: להפוך את Shelly לכתובת מספר 1 בעברית להבנת AET קריאייטיב. דורש קצב פרסום עקבי וזווית מובהקת.",
    missingItems: ["קצב פרסום קבוע בלינקדאין", "סדרת סמכות אחת מובהקת"],
    nextStep: "לקבע 2 פוסטי סמכות בשבוע ביומן הפרסום.",
    contentOpportunities: ["סדרת 'מאחורי הקסם'", "פוסט מיצוב אישי חזק"],
    progress: 55,
    createdAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "proj_collab_tool",
    name: "שיתוף פעולה: השקת כלי עריכת וידאו AI",
    type: "collaboration",
    status: "stuck",
    deadline: "2026-06-20",
    relatedDriveFolder: "Drive › שת״פים › Video Tool Launch",
    relatedDocs: [],
    relatedEmails: [
      { subject: "בריף שת״פ — תנאים וקריאייטיב", from: "מנהל שותפויות — VideoAI" },
    ],
    relatedCalendarEvents: [],
    relatedIdeas: [],
    summary:
      "הצעת שת״פ ממותג כלי וידאו. תקוע כי הבריף לא ברור והתמורה לא הוגדרה. צריך החלטה אם להמשיך.",
    missingItems: ["בריף קריאייטיב ברור", "הגדרת תמורה", "החלטה עקרונית"],
    nextStep: "לשלוח מייל שמבקש בריף ותמורה מדויקים — או לסגור את ההזדמנות.",
    contentOpportunities: [],
    progress: 15,
    createdAt: "2026-05-05T09:00:00Z",
  },
];

/* ---------- רעיונות ---------- */
export const mockIdeas: Idea[] = [
  {
    id: "idea_carousel_ai_workflow",
    title: "קרוסלה: ה-Workflow שבו אני מייצרת פוסט ב-12 דקות",
    description:
      "קרוסלת לינקדאין שמראה שלב-אחר-שלב איך נראה תהליך יצירת תוכן אמיתי עם AI — בלי לזייף שהכל קסם.",
    source: "manual",
    platform: "linkedin",
    contentType: "carousel",
    projectId: "proj_lecture_ai_brands",
    status: "almost-ready",
    classification: "post-idea",
    priorityScore: 86,
    classificationLabel: "create-today",
    urgency: "high",
    readiness: 78,
    recommendedAction: "להוסיף הוק פותח ו-CTA, ולשלוח לעיצוב.",
    hook: null,
    caption:
      "כולם מדברים על AI. מעטים מראים איך זה באמת נראה ביום-יום. אז הנה ה-workflow המלא שלי — בלי פילטרים.",
    script: null,
    visualPrompt: null,
    cta: null,
    publishDate: null,
    tags: ["workflow", "לינקדאין", "סמכות", "פרקטי"],
    missingItems: ["הוק פותח", "CTA"],
    notes: "התוכן קיים כמעט במלואו במסמך ההרצאה. צריך רק לעטוף.",
    createdAt: "2026-05-18T10:30:00Z",
    updatedAt: "2026-05-21T08:15:00Z",
  },
  {
    id: "idea_reels_prompt_fail",
    title: "רילס: הפרומפט שנכשל לי בשידור חי (ומה למדתי)",
    description:
      "סיפור אישי וכן על פרומפט שלא עבד מול קהל — והלקח שהפך אותי ליוצרת טובה יותר.",
    source: "manual",
    platform: "instagram",
    contentType: "reels",
    projectId: "proj_series_prompt_school",
    status: "in-progress",
    classification: "post-idea",
    priorityScore: 74,
    classificationLabel: "build-this-week",
    urgency: "medium",
    readiness: 45,
    recommendedAction: "לכתוב תסריט 45 שניות עם פתיח של 3 שניות.",
    hook: "הפרומפט הזה נכשל לי מול 200 איש.",
    caption: null,
    script: null,
    visualPrompt: null,
    cta: null,
    publishDate: null,
    tags: ["סיפור אישי", "פרומפטים", "רילס", "אותנטי"],
    missingItems: ["תסריט מלא", "רשימת קאטים", "טקסטים למסך"],
    notes: "זווית אישית חזקה — מבדלת אותי מתוכן 'AI מנצח' גנרי.",
    createdAt: "2026-05-12T14:00:00Z",
    updatedAt: "2026-05-20T09:00:00Z",
  },
  {
    id: "idea_linkedin_authority",
    title: "פוסט סמכות: 3 טעויות שמותגים עושים עם AET ב-2026",
    description:
      "פוסט לינקדאין דעתני שממצב את Shelly כמומחית — ביקורת מדויקת על מה שמותגים מפספסים.",
    source: "docs",
    platform: "linkedin",
    contentType: "post",
    projectId: "proj_brand_personal",
    status: "ready",
    classification: "post-idea",
    priorityScore: 91,
    classificationLabel: "publish-now",
    urgency: "high",
    readiness: 92,
    recommendedAction: "לפרסם היום בשעה 09:00 — חלון העלייה הכי טוב.",
    hook: "רוב המותגים משתמשים ב-AI בדיוק לא נכון. הנה איך לתקן.",
    caption:
      "עברתי על עשרות חשבונות מותג החודש. אותן 3 טעויות חוזרות שוב ושוב — וכולן ניתנות לתיקון.",
    script: null,
    visualPrompt: null,
    cta: "איזו מהטעויות הכי מוכרת לך? כתבי לי בתגובות.",
    publishDate: "2026-05-22",
    tags: ["סמכות", "מותגים", "לינקדאין", "דעתני"],
    missingItems: [],
    notes: "מוכן לחלוטין. פשוט לפרסם.",
    createdAt: "2026-05-15T11:00:00Z",
    updatedAt: "2026-05-21T19:00:00Z",
  },
  {
    id: "idea_prompt_layers",
    title: "פרק 3 לסדרה: שכבות בפרומפט — איך לחשוב כמו במאית",
    description:
      "פרק וידאו שמלמד לבנות פרומפט בשכבות: הקשר, סגנון, אילוצים, פלט.",
    source: "sheets",
    platform: "instagram",
    contentType: "reels",
    projectId: "proj_series_prompt_school",
    status: "inbox",
    classification: "future-content",
    priorityScore: 63,
    classificationLabel: "build-this-week",
    urgency: "medium",
    readiness: 25,
    recommendedAction: "לתזמן ליום הצילום ה-26.5 ולכתוב תסריט קודם.",
    hook: null,
    caption: null,
    script: null,
    visualPrompt: null,
    cta: null,
    publishDate: null,
    tags: ["סדרה", "פרומפטים", "חינוכי"],
    missingItems: ["תסריט", "דוגמאות חיות", "אינטרו"],
    notes: "הקהל ביקש המשך מפורש בתגובות לפרק 1.",
    createdAt: "2026-05-19T16:00:00Z",
    updatedAt: "2026-05-19T16:00:00Z",
  },
  {
    id: "idea_personal_story",
    title: "פוסט אישי: למה עזבתי משרה טובה כדי ללמד AI",
    description: "סיפור מעבר אישי שבונה חיבור רגשי וקרבה לקהל.",
    source: "manual",
    platform: "linkedin",
    contentType: "post",
    projectId: "proj_brand_personal",
    status: "almost-ready",
    classification: "post-idea",
    priorityScore: 79,
    classificationLabel: "create-today",
    urgency: "medium",
    readiness: 70,
    recommendedAction: "לחדד את הפתיח ולהוסיף משפט סיום עם לקח.",
    hook: "כולם אמרו לי שזו טעות.",
    caption:
      "לפני שנתיים קיבלתי החלטה שנראתה לא הגיונית לכולם. היום אני יודעת שזו הייתה הנכונה שעשיתי.",
    script: null,
    visualPrompt: null,
    cta: null,
    publishDate: null,
    tags: ["אישי", "מסע", "חיבור"],
    missingItems: ["משפט סיום", "CTA רך"],
    notes: "תוכן אישי עובד מצוין אצלי — מאזן את פוסטי הסמכות.",
    createdAt: "2026-05-10T08:00:00Z",
    updatedAt: "2026-05-20T12:00:00Z",
  },
  {
    id: "idea_prompt_pack",
    title: "פרומפט: מחולל קונספט קמפיין למותג ב-60 שניות",
    description: "פרומפט מתקדם בשכבות שמייצר קונספט קמפיין שלם ממשפט בריף קצר.",
    source: "drive",
    platform: "community",
    contentType: "prompt",
    projectId: null,
    status: "ready",
    classification: "prompt",
    priorityScore: 71,
    classificationLabel: "save-later",
    urgency: "low",
    readiness: 95,
    recommendedAction: "לשמור בספרייה ולשלב בניוזלטר הבא כבונוס.",
    hook: null,
    caption: null,
    script: null,
    visualPrompt: null,
    cta: null,
    publishDate: null,
    tags: ["פרומפט", "קמפיין", "בונוס"],
    missingItems: [],
    notes: "נכס איכותי — מצוין כ-lead magnet לקהילה.",
    createdAt: "2026-05-08T13:00:00Z",
    updatedAt: "2026-05-08T13:00:00Z",
  },
  {
    id: "idea_noise_generic",
    title: "פוסט: '10 כלי AI שחייבים להכיר'",
    description: "רשימת כלים גנרית. כולם עושים את זה.",
    source: "saved-link",
    platform: "instagram",
    contentType: "post",
    projectId: null,
    status: "parked",
    classification: "noise",
    priorityScore: 24,
    classificationLabel: "not-worth-time",
    urgency: "low",
    readiness: 30,
    recommendedAction: "לדלג. אין כאן בידול — השוק רווי.",
    hook: null,
    caption: null,
    script: null,
    visualPrompt: null,
    cta: null,
    publishDate: null,
    tags: ["רשימה", "גנרי"],
    missingItems: ["זווית מקורית", "בידול"],
    notes: "תוכן מסוג 'רשימת כלים' לא מבדל ולא בונה סמכות. לא שווה זמן.",
    createdAt: "2026-05-16T10:00:00Z",
    updatedAt: "2026-05-17T10:00:00Z",
  },
  {
    id: "idea_recycle_webinar",
    title: "מחזור: וובינר ישן על אוטומציה → סדרת 4 קרוסלות",
    description:
      "וובינר מ-2025 עם תוכן מצוין שכמעט לא נצפה. אפשר לחתוך אותו ל-4 קרוסלות.",
    source: "drive",
    platform: "linkedin",
    contentType: "carousel",
    projectId: null,
    status: "inbox",
    classification: "future-content",
    priorityScore: 67,
    classificationLabel: "recycle",
    urgency: "low",
    readiness: 55,
    recommendedAction: "לחלץ 4 רעיונות מרכזיים מהתמלול ולהפוך כל אחד לקרוסלה.",
    hook: null,
    caption: null,
    script: null,
    visualPrompt: null,
    cta: null,
    publishDate: null,
    tags: ["מחזור", "וובינר", "אוטומציה"],
    missingItems: ["תמלול מסונן", "עיצוב אחיד"],
    notes: "ROI מעולה — תוכן קיים, מאמץ נמוך.",
    createdAt: "2026-05-14T09:00:00Z",
    updatedAt: "2026-05-14T09:00:00Z",
  },
];

/* ---------- טרנדים ---------- */
export const mockTrends: Trend[] = [
  {
    id: "trend_video_model",
    title: "דור חדש של מודלי וידאו מייצר קליפים באורך מלא מטקסט",
    source: "gmail",
    sourceLabel: "ניוזלטר — The Rundown AI",
    summary:
      "כמה ספקיות הכריזו על מודלי וידאו שמייצרים סצנות ארוכות ועקביות ממשפט בודד, עם שליטה בתנועת מצלמה.",
    whyItMatters:
      "זה מזיז את הגבול בין 'גימיק' ל'הפקה אמיתית'. יוצרות וידאו צריכות להבין את זה השבוע, לא בעוד חודש.",
    whoIsItRelevantFor: "יוצרות וידאו, מותגים עם תקציבי הפקה, צוותי שיווק.",
    whyForCreators:
      "אפשר להפיק B-roll ופתיחים קולנועיים בלי צוות. זה משחרר זמן ותקציב לקריאייטיב.",
    whyForBrands:
      "עלות הפקת וידאו צונחת — מה שהיה קמפיין יקר הופך לבדיקה מהירה.",
    shellyPOV:
      "הכלי לא מחליף במאית — הוא מחליף את התירוץ 'אין לי תקציב'. הזווית שלי: איך לא לאבד טעם כשהכל נהיה זול.",
    trendType: "passing",
    urgencyScore: 88,
    productionEffort: "30min",
    recommendedFormat: "reels",
    recommendedPlatform: "instagram",
    cameraScript:
      "תפתחי עם הקליפ הכי מרשים שהמודל ייצר, ואז תגידי: 'יפה? עכשיו בואו נדבר על מה שזה באמת אומר לעבודה שלך.'",
    hooks: [
      "הפקת הווידאו שלך בדיוק נהייתה זולה ב-90%.",
      "צילמתי פרסומת שלמה בלי מצלמה. הנה מה שלמדתי.",
      "אם את עדיין משלמת על B-roll — תעצרי רגע.",
      "המודל הזה לא מרשים אותי. מה שהוא משחרר — כן.",
      "תקציב הפקה כבר לא תירוץ. אז מה כן?",
    ],
    cta: "תגידי לי — תנסי את זה בקמפיין הקרוב, או שזה עוד באזז?",
    categories: ["hot-trend", "content-opportunity", "for-reels"],
    finalDecision: "create-today",
    priorityScore: 89,
    status: "new",
    createdAt: "2026-05-22T06:30:00Z",
  },
  {
    id: "trend_agents_everywhere",
    title: "סוכני AI נכנסים כברירת מחדל לכל אפליקציית עבודה",
    source: "gmail",
    sourceLabel: "ניוזלטר — Ben's Bites",
    summary:
      "פלטפורמות עבודה גדולות משלבות סוכנים אוטונומיים שמבצעים משימות רב-שלביות בשם המשתמש.",
    whyItMatters:
      "השיחה עוברת מ'איך לכתוב פרומפט' ל'איך לנהל סוכן'. זה שינוי מהותי במיומנות.",
    whoIsItRelevantFor: "כל מי שעובד עם תוכן או תהליכים — כלומר כולם.",
    whyForCreators: "אפשר להאציל שלבים שלמים בתהליך התוכן ולהתמקד בקריאייטיב.",
    whyForBrands: "צוותים קטנים יכולים לתפקד כמו צוותים גדולים. שינוי תפעולי אמיתי.",
    shellyPOV:
      "הזווית שלי להרצאה: 'מפרומפטר למנהל'. המיומנות החדשה היא ניהול, לא כתיבה.",
    trendType: "strategic-asset",
    urgencyScore: 64,
    productionEffort: "deep-work",
    recommendedFormat: "lecture",
    recommendedPlatform: "lecture",
    cameraScript:
      "תסבירי בפשטות: 'פרומפט זה לבקש. סוכן זה להאציל. וזו מיומנות אחרת לגמרי.'",
    hooks: [
      "הפסיקי ללמוד פרומפטינג. למדי לנהל סוכנים.",
      "המיומנות הכי חשובה ב-2026 היא לא מה שחשבת.",
      "פרומפטר טוב כבר לא מספיק. הנה למה.",
      "הפכתי מכותבת פרומפטים למנהלת סוכנים. הנה ההבדל.",
      "אם זה לא בהרצאה הבאה שלך — את מאחור.",
    ],
    cta: "שמרי את זה — זה הולך להיות הנושא של הרבעון.",
    categories: ["content-opportunity", "for-lecture", "for-linkedin"],
    finalDecision: "save-lecture",
    priorityScore: 76,
    status: "new",
    createdAt: "2026-05-21T07:00:00Z",
  },
  {
    id: "trend_voice_clone",
    title: "שכפול קול בזמן אמת מגיע לכלי עריכה נפוצים",
    source: "saved-link",
    sourceLabel: "לינק שמור — בלוג מוצר",
    summary:
      "פיצ'ר שמאפשר לערוך נרטיב קולי ולתקן מילים בלי להקליט מחדש, בקול המקורי.",
    whyItMatters:
      "מקצר דרמטית עריכת פודקאסט ווידאו, אבל פותח שאלות אותנטיות.",
    whoIsItRelevantFor: "יוצרות פודקאסט ווידאו, אנשי שיווק תוכן.",
    whyForCreators: "פחות הקלטות חוזרות, יותר זמן לתוכן.",
    whyForBrands: "התאמת מסרים מהירה — אבל סיכון מוניטין אם לא שקופים.",
    shellyPOV:
      "זווית ביקורתית: כלי מעולה, אבל שקיפות מול הקהל היא לא רשות. זה תוכן דעתני טוב.",
    trendType: "evergreen",
    urgencyScore: 52,
    productionEffort: "30min",
    recommendedFormat: "post",
    recommendedPlatform: "linkedin",
    cameraScript:
      "תשאלי את הקהל ישירות: 'אם ערכתי משפט בקול שלי בלי להקליט — חייבת לספר לכם? אני חושבת שכן.'",
    hooks: [
      "ערכתי את הקול שלי בלי להקליט. זה מרגיש מוזר.",
      "הכלי הזה חוסך שעות. ופותח דילמה.",
      "מתי AI הופך מעריכה לזיוף?",
      "שקיפות היא הפיצ'ר. כל השאר זה רק טכנולוגיה.",
      "הייתי משתמשת בזה. אבל הייתי מספרת לך.",
    ],
    cta: "איפה את מותחת את הקו? בתגובות.",
    categories: ["content-opportunity", "for-linkedin"],
    finalDecision: "save-week",
    priorityScore: 61,
    status: "reviewed",
    createdAt: "2026-05-20T10:00:00Z",
  },
  {
    id: "trend_design_handoff",
    title: "כלי AI חדש מייצר מסך-לקוד מצילום מסך",
    source: "docs",
    sourceLabel: "Google Docs — הערות מחקר",
    summary:
      "כלי שממיר עיצוב סטטי לקוד עובד. רלוונטי לצוותי מוצר ועיצוב.",
    whyItMatters: "מקצר את המרחק בין רעיון למוצר, אבל פחות רלוונטי ישירות לקהל של Shelly.",
    whoIsItRelevantFor: "מפתחות, מעצבות מוצר.",
    whyForCreators: "רלוונטיות נמוכה — לא קהל הליבה.",
    whyForBrands: "רלוונטי לצוותי מוצר פנימיים בלבד.",
    shellyPOV: "מעניין, אבל לא הסיפור שלי. אם בכלל — אזכור קצר בניוזלטר.",
    trendType: "noise",
    urgencyScore: 22,
    productionEffort: "1hour",
    recommendedFormat: "post",
    recommendedPlatform: "newsletter",
    cameraScript: "—",
    hooks: [],
    cta: "—",
    categories: ["noise"],
    finalDecision: "ignore",
    priorityScore: 28,
    status: "reviewed",
    createdAt: "2026-05-19T12:00:00Z",
  },
  {
    id: "trend_creator_monetize",
    title: "פלטפורמות מוסיפות תשלום ישיר ליוצרות תוכן AI",
    source: "gmail",
    sourceLabel: "ניוזלטר — Creator Economy",
    summary:
      "מספר רשתות השיקו מסלולי הכנסה ייעודיים לתוכן שנוצר עם AI, עם תיוג שקיפות.",
    whyItMatters:
      "AET יוצא מהאזור האפור — נהיה מקור הכנסה לגיטימי ומתוגמל.",
    whoIsItRelevantFor: "יוצרות תוכן עצמאיות, מותגים אישיים.",
    whyForCreators: "הזדמנות הכנסה ישירה — אבל דורש עמידה בכללי שקיפות.",
    whyForBrands: "סיגנל שהקהל בשל לתוכן AET גלוי.",
    shellyPOV:
      "זה בדיוק המסר שלי כבר שנה: שקיפות = אמון = כסף. עכשיו יש לזה הוכחה.",
    trendType: "strategic-asset",
    urgencyScore: 70,
    productionEffort: "30min",
    recommendedFormat: "post",
    recommendedPlatform: "linkedin",
    cameraScript:
      "תגידי בחיוך: 'אמרתי לכם שזה מגיע. תוכן AET גלוי כבר לא מביך — הוא משתלם.'",
    hooks: [
      "תוכן AI כבר לא מילה גסה. הוא מקור הכנסה.",
      "שקיפות הפכה רגע מ-nice to have לכסף.",
      "אמרתי את זה לפני שנה. עכשיו יש מספרים.",
      "אם הסתרת שהשתמשת ב-AI — הפסדת כסף.",
      "הכלכלה של היוצרות השתנתה השבוע. הנה איך.",
    ],
    cta: "כבר חשבת על מסלול הכנסה כזה? בואי נדבר.",
    categories: ["hot-trend", "content-opportunity", "for-linkedin"],
    finalDecision: "publish-now",
    priorityScore: 82,
    status: "new",
    createdAt: "2026-05-22T05:45:00Z",
  },
  {
    id: "trend_image_consistency",
    title: "שליטה בעקביות דמות חוצה כל כלי יצירת התמונה",
    source: "drive",
    sourceLabel: "Drive — צילומי מסך שמורים",
    summary:
      "פיצ'ר שמשמר דמות אחידה לאורך סדרת תמונות — פותר את כאב הראש הכי גדול של יוצרות.",
    whyItMatters:
      "מאפשר ברנדינג ויזואלי עקבי — דמות מותג קבועה לאורך קמפיין שלם.",
    whoIsItRelevantFor: "יוצרות ויזואל, מנהלות מותג, מאיירות.",
    whyForCreators: "אפשר סוף סוף לבנות 'פרזנטורית AI' עקבית.",
    whyForBrands: "דמות מותג ויזואלית עקבית בלי צילומים חוזרים.",
    shellyPOV:
      "הזווית: 'בנו דמות מותג, לא תמונות יפות'. זה מתאים מצוין לדמו חי בהרצאה.",
    trendType: "evergreen",
    urgencyScore: 58,
    productionEffort: "1hour",
    recommendedFormat: "carousel",
    recommendedPlatform: "instagram",
    cameraScript:
      "תראי 6 תמונות של אותה דמות ותגידי: 'זו לא 6 תמונות. זו שפה ויזואלית של מותג.'",
    hooks: [
      "הפסיקי לייצר תמונות. תתחילי לייצר דמות.",
      "כאב הראש הכי גדול של יוצרות ויזואל — נפתר.",
      "מותג ויזואלי עקבי בלי צלם. הנה איך.",
      "תמונה יפה זה קל. עקביות זה מותג.",
      "בניתי פרזנטורית מותג ב-AI. היא לא משתנה.",
    ],
    cta: "שמרי לדמו בהרצאה הקרובה.",
    categories: ["content-opportunity", "for-demo", "for-carousel", "for-lecture"],
    finalDecision: "save-week",
    priorityScore: 68,
    status: "new",
    createdAt: "2026-05-21T15:00:00Z",
  },
  {
    id: "trend_hype_drama",
    title: "דרמת רשת סביב הכרזה מנופחת של סטארטאפ AI",
    source: "saved-link",
    sourceLabel: "לינק שמור — ציוץ ויראלי",
    summary:
      "הכרזה שהתבררה כמוגזמת יצרה גל תגובות. הרבה רעש, מעט מהות.",
    whyItMatters: "כמעט לא. זה באזז שייעלם תוך ימים.",
    whoIsItRelevantFor: "כמעט אף אחד באופן מעשי.",
    whyForCreators: "אין ערך — תוכן תגובתי לרעש שוחק אמון.",
    whyForBrands: "להתרחק. אסוציאציה לדרמה לא מועילה.",
    shellyPOV: "זה רעש. הקול שלי לא נשרף על דרמות.",
    trendType: "noise",
    urgencyScore: 12,
    productionEffort: "15min",
    recommendedFormat: "post",
    recommendedPlatform: "linkedin",
    cameraScript: "—",
    hooks: [],
    cta: "—",
    categories: ["noise"],
    finalDecision: "ignore",
    priorityScore: 16,
    status: "reviewed",
    createdAt: "2026-05-22T08:00:00Z",
  },
];

/* ---------- ספריית תוכן ---------- */
export const mockLibrary: ContentLibraryItem[] = [
  {
    id: "lib_prompt_campaign",
    assetName: "פרומפט: מחולל קונספט קמפיין ב-60 שניות",
    type: "prompt",
    projectId: null,
    platform: "community",
    contentType: "prompt",
    tags: ["פרומפט", "קמפיין", "מתקדם"],
    driveLink: "#drive/prompts/campaign-generator",
    source: "drive",
    bestUse: "Lead magnet לקהילה או בונוס בניוזלטר.",
    publishedStatus: "ready",
    duplicateFlag: false,
    readyToPublish: true,
    goodForRecycle: true,
    goodForLecture: true,
    notes: "אחד הפרומפטים החזקים במאגר.",
    createdAt: "2026-05-08T13:00:00Z",
  },
  {
    id: "lib_post_authority_published",
    assetName: "פוסט: 'AI לא יחליף אותך. מי שיודע להשתמש בו — כן'",
    type: "published-post",
    projectId: "proj_brand_personal",
    platform: "linkedin",
    contentType: "post",
    tags: ["סמכות", "ויראלי", "מיצוב"],
    driveLink: "#drive/published/ai-wont-replace",
    source: "manual",
    bestUse: "רפרנס לסגנון פוסט סמכות מנצח. ראוי למחזור כקרוסלה.",
    publishedStatus: "published",
    duplicateFlag: false,
    readyToPublish: false,
    goodForRecycle: true,
    goodForLecture: false,
    notes: "הפוסט הכי מוצלח של הרבעון.",
    createdAt: "2026-04-22T09:00:00Z",
  },
  {
    id: "lib_hooks_pack",
    assetName: "מאגר הוקים: 30 פתיחים מנצחים לרילס",
    type: "hook",
    projectId: null,
    platform: "instagram",
    contentType: "reels",
    tags: ["הוקים", "רילס", "מאגר"],
    driveLink: "#drive/assets/hooks-pack",
    source: "manual",
    bestUse: "להתחיל מכאן כשכותבים תסריט רילס חדש.",
    publishedStatus: "unpublished-valuable",
    duplicateFlag: false,
    readyToPublish: false,
    goodForRecycle: true,
    goodForLecture: false,
    notes: "נכס עבודה פנימי — שווה זהב.",
    createdAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "lib_lecture_deck",
    assetName: "מצגת: AI שמוכר — טיוטה 3",
    type: "lecture-material",
    projectId: "proj_lecture_ai_brands",
    platform: "lecture",
    contentType: "lecture",
    tags: ["הרצאה", "מצגת", "מותגים"],
    driveLink: "#drive/lectures/ai-sells-deck",
    source: "drive",
    bestUse: "בסיס להרצאת הכנס ב-4.6. אפשר לחלץ ממנה 3 קרוסלות.",
    publishedStatus: "draft",
    duplicateFlag: false,
    readyToPublish: false,
    goodForRecycle: true,
    goodForLecture: true,
    notes: "חסר דמו שלישי.",
    createdAt: "2026-05-05T11:00:00Z",
  },
  {
    id: "lib_script_reels1",
    assetName: "תסריט: פרק 1 בית הספר לפרומפטים",
    type: "script",
    projectId: "proj_series_prompt_school",
    platform: "instagram",
    contentType: "reels",
    tags: ["תסריט", "סדרה", "פרומפטים"],
    driveLink: "#drive/scripts/prompt-school-1",
    source: "docs",
    bestUse: "תבנית לתסריטי הסדרה הבאים.",
    publishedStatus: "published",
    duplicateFlag: false,
    readyToPublish: false,
    goodForRecycle: false,
    goodForLecture: false,
    notes: "מבנה עבד מצוין — לשכפל.",
    createdAt: "2026-04-12T10:00:00Z",
  },
  {
    id: "lib_webinar_old",
    assetName: "הקלטת וובינר: אוטומציה לעסקים קטנים (2025)",
    type: "file",
    projectId: null,
    platform: null,
    contentType: null,
    tags: ["וובינר", "אוטומציה", "ארכיון"],
    driveLink: "#drive/archive/webinar-automation",
    source: "drive",
    bestUse: "מכרה זהב למחזור — אפשר 4 קרוסלות ופוסט אחד.",
    publishedStatus: "unpublished-valuable",
    duplicateFlag: false,
    readyToPublish: false,
    goodForRecycle: true,
    goodForLecture: true,
    notes: "תוכן מצוין שכמעט לא נצפה.",
    createdAt: "2025-11-18T10:00:00Z",
  },
  {
    id: "lib_cta_bank",
    assetName: "מאגר CTA: 15 קריאות לפעולה לפי פלטפורמה",
    type: "cta",
    projectId: null,
    platform: null,
    contentType: null,
    tags: ["CTA", "מאגר", "המרה"],
    driveLink: "#drive/assets/cta-bank",
    source: "manual",
    bestUse: "להשלים כל פוסט שחסר לו סיום חזק.",
    publishedStatus: "unpublished-valuable",
    duplicateFlag: false,
    readyToPublish: false,
    goodForRecycle: false,
    goodForLecture: false,
    notes: "נכס עבודה שימושי יומיומי.",
    createdAt: "2026-02-14T10:00:00Z",
  },
  {
    id: "lib_visual_ref",
    assetName: "לוח רפרנס ויזואלי: סגנון מותג אישי",
    type: "reference",
    projectId: "proj_brand_personal",
    platform: "instagram",
    contentType: null,
    tags: ["ויזואל", "מותג", "רפרנס"],
    driveLink: "#drive/brand/visual-board",
    source: "drive",
    bestUse: "להצמיד לכל בריף ויזואלי כדי לשמור אחידות.",
    publishedStatus: "unpublished-valuable",
    duplicateFlag: false,
    readyToPublish: false,
    goodForRecycle: false,
    goodForLecture: false,
    notes: "—",
    createdAt: "2026-03-02T10:00:00Z",
  },
  {
    id: "lib_dup_hooks",
    assetName: "הוקים — עותק ישן (כפילות)",
    type: "hook",
    projectId: null,
    platform: "instagram",
    contentType: "reels",
    tags: ["הוקים", "כפילות"],
    driveLink: "#drive/assets/hooks-old",
    source: "drive",
    bestUse: "כנראה כפילות של מאגר ההוקים הראשי — לבדוק ולמחוק.",
    publishedStatus: "draft",
    duplicateFlag: true,
    readyToPublish: false,
    goodForRecycle: false,
    goodForLecture: false,
    notes: "מסומן ככפילות — דורש אישור לפני מחיקה.",
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "lib_draft_newsletter",
    assetName: "טיוטת ניוזלטר: 'מה למדתי החודש על AI'",
    type: "draft",
    projectId: null,
    platform: "newsletter",
    contentType: "newsletter",
    tags: ["ניוזלטר", "טיוטה"],
    driveLink: "#docs/drafts/monthly-newsletter",
    source: "docs",
    bestUse: "להשלים ולשלוח בסוף החודש.",
    publishedStatus: "draft",
    duplicateFlag: false,
    readyToPublish: false,
    goodForRecycle: false,
    goodForLecture: false,
    notes: "חסרות 2 פסקאות וסיכום.",
    createdAt: "2026-05-15T10:00:00Z",
  },
  {
    id: "lib_link_research",
    assetName: "לינק: מחקר על שיעורי אמון בתוכן AI",
    type: "link",
    projectId: null,
    platform: null,
    contentType: null,
    tags: ["מחקר", "אמון", "רפרנס"],
    driveLink: "#links/trust-research",
    source: "saved-link",
    bestUse: "מקור מספרים מצוין לפוסט סמכות או שקופית הרצאה.",
    publishedStatus: "unpublished-valuable",
    duplicateFlag: false,
    readyToPublish: false,
    goodForRecycle: false,
    goodForLecture: true,
    notes: "נתונים תומכים לזווית השקיפות.",
    createdAt: "2026-05-09T10:00:00Z",
  },
  {
    id: "lib_carousel_template",
    assetName: "תבנית קרוסלה: גריד 8 שקופיות מותג",
    type: "project-asset",
    projectId: "proj_brand_personal",
    platform: "linkedin",
    contentType: "carousel",
    tags: ["תבנית", "קרוסלה", "עיצוב"],
    driveLink: "#drive/templates/carousel-8",
    source: "drive",
    bestUse: "תבנית בסיס לכל קרוסלה — שומרת אחידות מותג.",
    publishedStatus: "ready",
    duplicateFlag: false,
    readyToPublish: true,
    goodForRecycle: true,
    goodForLecture: false,
    notes: "—",
    createdAt: "2026-02-28T10:00:00Z",
  },
];

/* ---------- הזדמנויות (Gmail Opportunity Assistant) ---------- */
export const mockOpportunities: Opportunity[] = [
  {
    id: "opp_lecture_invite",
    source: "gmail",
    title: "הזמנה להרצאת מליאה — כנס חדשנות שיווק",
    from: "ועדת תוכן — Innovation Summit",
    summary:
      "הזמנה להרצאת מליאה בת 40 דקות מול ~500 משתתפים על AI בשיווק. ביקשו תשובה עד סוף השבוע.",
    type: "lecture-invite",
    importance: "high",
    urgency: "high",
    recommendedAction:
      "להגיב חיובית עקרונית ולבקש פרטים: תאריך, תקציב, קהל. הזדמנות מיצוב מצוינת.",
    shouldDraftReply: true,
    shouldTurnIntoContent: false,
    shouldSaveToProject: true,
    shouldCreateReminder: true,
    status: "new",
    relatedProjectId: null,
    createdAt: "2026-05-21T08:30:00Z",
  },
  {
    id: "opp_client_inquiry",
    source: "gmail",
    title: "פנייה: ליווי AI לצוות תוכן בחברת ריטייל",
    from: "סמנכ״לית שיווק — Retail Brand",
    summary:
      "חברת ריטייל מבקשת הצעה לליווי בן 8 שבועות לצוות התוכן שלה. תקציב נראה רציני.",
    type: "client-inquiry",
    importance: "high",
    urgency: "medium",
    recommendedAction:
      "לשלוח שאלון אבחון קצר לפני שמתמחרים. דומה מאוד לפרויקט הפינטק שמסתיים.",
    shouldDraftReply: true,
    shouldTurnIntoContent: false,
    shouldSaveToProject: true,
    shouldCreateReminder: true,
    status: "new",
    relatedProjectId: "proj_client_fintech",
    createdAt: "2026-05-20T14:00:00Z",
  },
  {
    id: "opp_collab",
    source: "gmail",
    title: "הצעת שת״פ — מותג כלי וידאו AI",
    from: "מנהל שותפויות — VideoAI",
    summary:
      "הצעה לקדם כלי עריכת וידאו. הבריף עמום והתמורה לא הוגדרה.",
    type: "collaboration",
    importance: "medium",
    urgency: "low",
    recommendedAction:
      "לבקש בריף ותמורה מדויקים לפני כל התחייבות. אם לא יגיע — לסגור.",
    shouldDraftReply: true,
    shouldTurnIntoContent: false,
    shouldSaveToProject: true,
    shouldCreateReminder: false,
    status: "reviewed",
    relatedProjectId: "proj_collab_tool",
    createdAt: "2026-05-18T11:00:00Z",
  },
  {
    id: "opp_followup",
    source: "gmail",
    title: "פולואפ נדרש — סבב הערות לקוח פינטק",
    from: "מנהלת תוכן — Fintech Co",
    summary:
      "הלקוח שלח הערות אחרונות על המתווה ומחכה לתגובה כבר 3 ימים.",
    type: "follow-up",
    importance: "high",
    urgency: "critical",
    recommendedAction:
      "להגיב היום. עיכוב נוסף פוגע בסגירה חלקה של הפרויקט.",
    shouldDraftReply: true,
    shouldTurnIntoContent: false,
    shouldSaveToProject: true,
    shouldCreateReminder: true,
    status: "new",
    relatedProjectId: "proj_client_fintech",
    createdAt: "2026-05-19T09:00:00Z",
  },
  {
    id: "opp_newsletter",
    source: "gmail",
    title: "ניוזלטר חשוב — דוח מגמות יוצרים רבעוני",
    from: "Creator Economy Report",
    summary:
      "דוח רבעוני עם נתונים על הכנסות יוצרים ותוכן AI. חומר גלם מצוין לפוסט סמכות.",
    type: "important-newsletter",
    importance: "medium",
    urgency: "low",
    recommendedAction:
      "לשמור לספרייה כרפרנס נתונים. להפוך זווית אחת לפוסט.",
    shouldDraftReply: false,
    shouldTurnIntoContent: true,
    shouldSaveToProject: false,
    shouldCreateReminder: false,
    status: "new",
    relatedProjectId: null,
    createdAt: "2026-05-22T06:00:00Z",
  },
  {
    id: "opp_quote",
    source: "gmail",
    title: "בקשת הצעת מחיר — סדנת AI פנים-ארגונית",
    from: "מנהלת L&D — Tech Company",
    summary:
      "חברת טכנולוגיה מבקשת הצעת מחיר לסדנה בת חצי יום ל-25 עובדים.",
    type: "quote-request",
    importance: "medium",
    urgency: "medium",
    recommendedAction:
      "לשלוח הצעת מחיר סטנדרטית לסדנה. תהליך קצר ומוכר.",
    shouldDraftReply: true,
    shouldTurnIntoContent: false,
    shouldSaveToProject: false,
    shouldCreateReminder: true,
    status: "new",
    relatedProjectId: null,
    createdAt: "2026-05-21T16:00:00Z",
  },
];

/* ---------- פעולות מומלצות (מסך "מה לעשות עכשיו") ---------- */
export const mockNextActions: NextAction[] = [
  {
    id: "na_publish_authority",
    title: "לפרסם עכשיו: פוסט הסמכות '3 טעויות של מותגים עם AI'",
    whyNow:
      "הפוסט מוכן ב-92%, והשעה 09:00 היום היא חלון החשיפה הכי חזק בלינקדאין. כל שעה שעוברת היא הגעה אורגנית שאבדה.",
    whyOnBrand:
      "פוסט דעתני וביקורתי שממצב אותך כמומחית — בדיוק הקול שבונה את 'הכתובת מספר 1 ל-AI בעברית'.",
    urgency: "high",
    effort: "15min",
    platform: "linkedin",
    whatsMissing: [],
    nextStep: "לעבור הגהה אחרונה, לוודא שורת פתיחה חזקה, ולפרסם.",
    strategicReason:
      "עקביות בפוסטי סמכות היא המנוע של המיצוב. פוסט מוכן שלא מתפרסם הוא הפסד נטו.",
    ctaLabel: "פתחי את הפוסט ופרסמי",
    relatedMode: ["quick-15", "linkedin"],
    sourceType: "idea",
    sourceId: "idea_linkedin_authority",
  },
  {
    id: "na_react_video_trend",
    title: "להגיב לטרנד החם: דור חדש של מודלי וידאו",
    whyNow:
      "הטרנד פרץ הבוקר וציון הדחיפות שלו 88. חלון התגובה הוא 24-48 שעות — אחר כך הוא כבר 'ישן'.",
    whyOnBrand:
      "את לא מדווחת על כלים — את נותנת פרשנות. הזווית 'איך לא לאבד טעם כשהכל זול' מבדלת אותך מכל מי שרק יחגוג.",
    urgency: "critical",
    effort: "30min",
    platform: "instagram",
    whatsMissing: ["רילס מצולם", "טקסטים למסך"],
    nextStep: "לצלם רילס של 30 שניות עם ההוק 'תקציב הפקה כבר לא תירוץ'.",
    strategicReason:
      "מהירות תגובה לטרנדים היא מטבע הסמכות. להגיב נכון ומהר שווה יותר מלהגיב מושלם ומאוחר.",
    ctaLabel: "צרי רילס תגובה עכשיו",
    relatedMode: ["react-trend", "on-camera", "viral"],
    sourceType: "trend",
    sourceId: "trend_video_model",
  },
  {
    id: "na_reply_fintech",
    title: "להגיב לפולואפ של לקוח הפינטק",
    whyNow:
      "הלקוח מחכה 3 ימים לתגובה על סבב ההערות. דדליין הפרויקט ב-30.5 — עיכוב מסכן סגירה חלקה.",
    whyOnBrand:
      "מקצוענות בליווי לקוחות היא מה שמייצר את ההמלצות והקייסים שמזינים את ההרצאות.",
    urgency: "critical",
    effort: "15min",
    platform: "linkedin",
    whatsMissing: ["תגובה לסבב ההערות"],
    nextStep: "לעבור על ההערות, לאשר את הברורות, ולנסח טיוטת תשובה.",
    strategicReason:
      "פרויקט שנסגר טוב = קייס סטדי = תוכן סמכות עתידי. שווה 15 דקות עכשיו.",
    ctaLabel: "הכיני טיוטת תשובה",
    relatedMode: ["quick-15", "organize"],
    sourceType: "opportunity",
    sourceId: "opp_followup",
  },
  {
    id: "na_carousel_workflow",
    title: "לסגור את קרוסלת ה-Workflow",
    whyNow:
      "הקרוסלה מוכנה ב-78% — חסרים רק הוק ו-CTA. זה תוכן 'כמעט מוכן' שחבל שיתקע.",
    whyOnBrand:
      "להראות את התהליך האמיתי, בלי לזייף שהכל קסם — זה הבידול המרכזי שלך.",
    urgency: "high",
    effort: "30min",
    platform: "linkedin",
    whatsMissing: ["הוק פותח", "CTA"],
    nextStep: "לייצר 5 הוקים, לבחור אחד, להוסיף CTA ולשלוח לעיצוב.",
    strategicReason:
      "תוכן 'כמעט מוכן' הוא ה-ROI הכי גבוה במערכת — מעט עבודה, פרסום מובטח.",
    ctaLabel: "סגרי את הקרוסלה",
    relatedMode: ["carousel", "linkedin"],
    sourceType: "idea",
    sourceId: "idea_carousel_ai_workflow",
  },
  {
    id: "na_lecture_demo",
    title: "להקליט את הדמו השלישי להרצאת הכנס",
    whyNow:
      "ההרצאה ב-4.6 — נשארו פחות משבועיים. הדמו השלישי הוא הפריט החוסם היחיד.",
    whyOnBrand:
      "דמו חי הוא מה שהופך הרצאה ל'וואו'. זה מבסס אותך כמי שלא רק מדברת — אלא עושה.",
    urgency: "high",
    effort: "deep-work",
    platform: "lecture",
    whatsMissing: ["דמו שלישי מוקלט", "שיבוץ במצגת"],
    nextStep: "לחסום שעה ביומן, להקליט את הדמו ולשבץ במצגת.",
    strategicReason:
      "הרצאה חזקה מייצרת חודש שלם של תוכן נגזר. ההשקעה הזו מחזירה את עצמה כמה פעמים.",
    ctaLabel: "פתחי את תוכנית הדמו",
    relatedMode: ["lecture"],
    sourceType: "project",
    sourceId: "proj_lecture_ai_brands",
  },
  {
    id: "na_recycle_webinar",
    title: "למחזר את הוובינר הישן ל-4 קרוסלות",
    whyNow:
      "יש לך תוכן מעולה מ-2025 שכמעט לא נצפה. מאמץ נמוך, תשואה גבוהה.",
    whyOnBrand:
      "תוכן ה-evergreen שלך טוב מכדי להיקבר. מחזור חכם הוא סימן ליוצרת אסטרטגית.",
    urgency: "low",
    effort: "1hour",
    platform: "linkedin",
    whatsMissing: ["תמלול מסונן", "עיצוב אחיד"],
    nextStep: "לחלץ 4 רעיונות מרכזיים מהתמלול ולהתחיל מהראשון.",
    strategicReason:
      "מחזור תוכן איכותי משחרר אותך מלייצר הכל מאפס — וזה מה שמאפשר עקביות.",
    ctaLabel: "התחילי למחזר",
    relatedMode: ["recycle", "organize"],
    sourceType: "idea",
    sourceId: "idea_recycle_webinar",
  },
];

/* ---------- דוחות שבועיים ---------- */
export const mockWeeklyReviews: WeeklyReview[] = [
  {
    id: "wr_2026_w21",
    week: "18-24 במאי 2026",
    activeProjects: [
      "הרצאה: AI שמוכר",
      "סדרת בית הספר לפרומפטים",
      "ליווי לקוח פינטק",
    ],
    newIdeas: [
      "קרוסלת ה-Workflow",
      "פוסט אישי: למה עזבתי משרה טובה",
      "מחזור הוובינר ל-4 קרוסלות",
    ],
    readyToPublish: ["פוסט סמכות: 3 טעויות של מותגים עם AI"],
    publishedContent: ["פרק 1 — בית הספר לפרומפטים"],
    stuckContent: [
      "שת״פ כלי הווידאו — תקוע על בריף לא ברור",
      "פרק 3 לסדרה — אין עדיין תסריט",
    ],
    identifiedTrends: [
      "דור חדש של מודלי וידאו",
      "תשלום ישיר ליוצרות תוכן AI",
      "סוכני AI בכל אפליקציה",
    ],
    missedTrends: ["גל השיח על עקביות דמות — אפשר היה להגיב מוקדם יותר"],
    notWorthContinuing: [
      "פוסט '10 כלי AI שחייבים' — גנרי, בלי בידול",
      "דרמת ההכרזה המנופחת — רעש",
    ],
    makeSeries: ["בית הספר לפרומפטים — לקבע קצב שבועי"],
    lectureMaterial: [
      "סוכני AI — הזווית 'מפרומפטר למנהל'",
      "עקביות דמות — דמו חי",
    ],
    nextWeekPublishing: [
      "פוסט הסמכות (להעלות מיד)",
      "רילס תגובה לטרנד הווידאו",
      "קרוסלת ה-Workflow",
    ],
    recommendations: [
      "לפרסם את פוסט הסמכות היום — הוא יושב מוכן ומבזבז חשיפה.",
      "להגיב לטרנד הווידאו תוך 48 שעות עם רילס קצר.",
      "לסגור את הפולואפ ללקוח הפינטק לפני שהוא פוגע בפרויקט.",
    ],
    topAction:
      "לפרסם את פוסט הסמכות 'שלוש טעויות' — הכי קל, הכי משפיע, מוכן עכשיו.",
    strategicInsight:
      "השבוע ייצרת הרבה רעיונות אבל פרסמת מעט. הצוואר הבקבוק שלך הוא לא חוסר רעיונות — הוא הסגירה האחרונה. בשבוע הבא: פחות 'להתחיל', יותר 'לפרסם'. קבעי 3 חלונות פרסום קבועים ביומן, והתייחסי אליהם כמו לפגישות אמיתיות. תוכן מוכן שלא יוצא החוצה לא קיים.",
    createdAt: "2026-05-22T07:00:00Z",
  },
  {
    id: "wr_2026_w20",
    week: "11-17 במאי 2026",
    activeProjects: ["הרצאה: AI שמוכר", "סדרת בית הספר לפרומפטים"],
    newIdeas: ["רילס הפרומפט שנכשל", "פרומפט מחולל קמפיין"],
    readyToPublish: ["פרק 1 — בית הספר לפרומפטים"],
    publishedContent: ["פוסט: AI לא יחליף אותך"],
    stuckContent: ["מצגת ההרצאה — חסר דמו"],
    identifiedTrends: ["שכפול קול בזמן אמת", "עקביות דמות בתמונות"],
    missedTrends: [],
    notWorthContinuing: ["כלי מסך-לקוד — לא קהל הליבה"],
    makeSeries: ["בית הספר לפרומפטים"],
    lectureMaterial: ["שקופית שקיפות מבוססת נתונים"],
    nextWeekPublishing: ["פרק 1 לסדרה", "פוסט הסמכות"],
    recommendations: [
      "להעלות את פרק 1 לסדרה — מוכן.",
      "לחסום זמן לדמו ההרצאה.",
      "לשמור את טרנד הקול לזווית ביקורתית.",
    ],
    topAction: "להעלות את פרק 1 של בית הספר לפרומפטים.",
    strategicInsight:
      "שבוע טוב של בנייה. הסדרה תפסה תאוצה והקהל מגיב. שמרי על המומנטום — עקביות מנצחת ברק חד-פעמי.",
    createdAt: "2026-05-15T07:00:00Z",
  },
];

/* ---------- תוכן שפורסם ---------- */
export const mockPublished: PublishedContentItem[] = [
  {
    id: "pub_ai_wont_replace",
    title: "AI לא יחליף אותך. מי שיודע להשתמש בו — כן",
    platform: "linkedin",
    publishDate: "2026-05-13",
    link: "#published/ai-wont-replace",
    sourceIdeaId: null,
    performanceNotes:
      "הפוסט הכי מוצלח של הרבעון. שיעור שמירה גבוה, הרבה שיתופים מקצועיים.",
    repurposeSuggestions: [
      "להפוך לקרוסלה של 8 שקופיות",
      "לפתח לתסריט רילס אישי",
      "להשתמש כשקופית פתיחה בהרצאה",
    ],
    metrics: { views: 24800, engagement: 1320, saves: 410 },
  },
  {
    id: "pub_prompt_school_1",
    title: "בית הספר לפרומפטים — פרק 1: למה הפרומפט שלך לא עובד",
    platform: "instagram",
    publishDate: "2026-05-16",
    link: "#published/prompt-school-1",
    sourceIdeaId: null,
    performanceNotes:
      "שמירות גבוהות מאוד. הקהל ביקש המשך מפורש בתגובות.",
    repurposeSuggestions: [
      "לחתוך גרסה קצרה לטיקטוק",
      "להפוך לקרוסלה מקבילה ללינקדאין",
    ],
    metrics: { views: 18200, engagement: 980, saves: 540 },
  },
  {
    id: "pub_newsletter_april",
    title: "ניוזלטר אפריל: 3 דברים שכל יוצרת צריכה לדעת על AI",
    platform: "newsletter",
    publishDate: "2026-04-30",
    link: "#published/newsletter-april",
    sourceIdeaId: null,
    performanceNotes: "שיעור פתיחה מעל הממוצע. הקליקו בעיקר על הפרומפט המצורף.",
    repurposeSuggestions: ["להפוך כל סעיף לפוסט נפרד"],
    metrics: { views: 3100, engagement: 620, saves: 0 },
  },
  {
    id: "pub_carousel_myths",
    title: "קרוסלה: 5 מיתוסים על AET שהגיע הזמן לקבור",
    platform: "linkedin",
    publishDate: "2026-05-06",
    link: "#published/carousel-myths",
    sourceIdeaId: null,
    performanceNotes: "ביצועים בינוניים-טובים. השקופית האחרונה (CTA) הניעה תגובות.",
    repurposeSuggestions: [
      "לרענן עם דוגמאות 2026 ולפרסם מחדש",
      "להפוך לרילס מהיר",
    ],
    metrics: { views: 11400, engagement: 510, saves: 230 },
  },
  {
    id: "pub_reels_tool",
    title: "רילס: ניסיתי כלי AET חדש כל יום במשך שבוע",
    platform: "instagram",
    publishDate: "2026-05-09",
    link: "#published/reels-tool-week",
    sourceIdeaId: null,
    performanceNotes: "הגעה טובה, אבל שיעור שמירה נמוך — תוכן בידורי יותר מערכי.",
    repurposeSuggestions: ["לבחור את הכלי החזק ולעשות עליו פרק עומק"],
    metrics: { views: 32100, engagement: 1450, saves: 180 },
  },
  {
    id: "pub_tiktok_prompt",
    title: "טיקטוק: הפרומפט שמשנה איך את כותבת מיילים",
    platform: "tiktok",
    publishDate: "2026-05-11",
    link: "#published/tiktok-email-prompt",
    sourceIdeaId: null,
    performanceNotes: "ביצועים יפים בטיקטוק — תוכן פרקטי קצר עובד שם הכי טוב.",
    repurposeSuggestions: ["לשכפל את הפורמט עם פרומפטים נוספים — סדרה פוטנציאלית"],
    metrics: { views: 41000, engagement: 2200, saves: 760 },
  },
];

/* ---------- אירועי יומן (Google Calendar — mock) ---------- */
export interface CalendarEvent {
  id: string;
  title: string;
  date: string; // ISO date
  type: "lecture" | "shoot" | "meeting" | "deadline" | "publish";
  relatedProjectId: string | null;
}

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "cal_publish_authority",
    title: "פרסום מתוכנן: פוסט סמכות לינקדאין",
    date: "2026-05-22",
    type: "publish",
    relatedProjectId: "proj_brand_personal",
  },
  {
    id: "cal_shoot_ep2",
    title: "צילום פרק 2 — בית הספר לפרומפטים",
    date: "2026-05-26",
    type: "shoot",
    relatedProjectId: "proj_series_prompt_school",
  },
  {
    id: "cal_client_wrap",
    title: "סשן סיכום עם לקוח הפינטק",
    date: "2026-05-29",
    type: "meeting",
    relatedProjectId: "proj_client_fintech",
  },
  {
    id: "cal_fintech_deadline",
    title: "דדליין מסירה — פרויקט פינטק",
    date: "2026-05-30",
    type: "deadline",
    relatedProjectId: "proj_client_fintech",
  },
  {
    id: "cal_lecture",
    title: "הרצאה — כנס שיווק דיגיטלי",
    date: "2026-06-04",
    type: "lecture",
    relatedProjectId: "proj_lecture_ai_brands",
  },
  {
    id: "cal_collab_deadline",
    title: "דדליין החלטה — שת״פ כלי וידאו",
    date: "2026-06-20",
    type: "deadline",
    relatedProjectId: "proj_collab_tool",
  },
  {
    id: "cal_publish_carousel",
    title: "פרסום מתוכנן: קרוסלת Workflow",
    date: "2026-05-27",
    type: "publish",
    relatedProjectId: "proj_lecture_ai_brands",
  },
  {
    id: "cal_publish_reels",
    title: "פרסום מתוכנן: רילס תגובה לטרנד וידאו",
    date: "2026-05-23",
    type: "publish",
    relatedProjectId: null,
  },
];

/* ---------- חדשות הבוקר — 6 כותרות להיום ---------- */
export const mockNews: NewsHeadline[] = [
  {
    id: "news_video_models",
    rank: 1,
    title: "דור חדש של מודלי וידאו מייצר קליפים באורך מלא ממשפט בודד",
    summary:
      "כמה ספקיות הציגו מודלים שמפיקים סצנות וידאו ארוכות ועקביות, עם שליטה בתנועת מצלמה — מטקסט בלבד.",
    source: "The Rundown AI",
    category: "ai-model",
    whyItMatters:
      "הגבול בין 'גימיק' ל'הפקה אמיתית' זז. עלות הפקת וידאו צונחת — וזה משנה איך מתכננים תוכן.",
    suggestedAngle:
      "אל תחגגי את הכלי. שאלי איך לא לאבד טעם כשהכל נהיה זול — זה הבידול שלך.",
    hotness: 93,
    worthPosting: true,
    recommendedPlatform: "instagram",
    createdAt: "2026-05-22T05:40:00Z",
  },
  {
    id: "news_creator_pay",
    rank: 2,
    title: "רשתות חברתיות משיקות תשלום ישיר ליוצרות תוכן AI",
    summary:
      "מספר פלטפורמות פתחו מסלולי הכנסה ייעודיים לתוכן שנוצר עם AI, בתנאי תיוג שקיפות.",
    source: "Creator Economy Report",
    category: "creator-economy",
    whyItMatters:
      "תוכן AI יוצא מהאזור האפור והופך למקור הכנסה לגיטימי ומתוגמל.",
    suggestedAngle:
      "'אמרתי לכם שזה מגיע' — שקיפות = אמון = כסף. עכשיו יש לזה הוכחה.",
    hotness: 85,
    worthPosting: true,
    recommendedPlatform: "linkedin",
    createdAt: "2026-05-22T05:55:00Z",
  },
  {
    id: "news_agents",
    rank: 3,
    title: "סוכני AI הופכים לברירת מחדל בכלי העבודה הגדולים",
    summary:
      "פלטפורמות עבודה מרכזיות שילבו סוכנים אוטונומיים שמבצעים משימות רב-שלביות בשם המשתמש.",
    source: "Ben's Bites",
    category: "ai-tool",
    whyItMatters:
      "המיומנות עוברת מ'איך לכתוב פרומפט' ל'איך לנהל סוכן'. שינוי מהותי.",
    suggestedAngle:
      "'מפרומפטר למנהל' — הסבירי שזו מיומנות חדשה לגמרי. מצוין להרצאה.",
    hotness: 79,
    worthPosting: true,
    recommendedPlatform: "linkedin",
    createdAt: "2026-05-22T06:05:00Z",
  },
  {
    id: "news_video_algo",
    rank: 4,
    title: "עדכון אלגוריתם: וידאו קצר ואותנטי מקבל דחיפת חשיפה",
    summary:
      "רשת חברתית גדולה עדכנה את האלגוריתם כך שמעדיף וידאו קצר, אנושי ולא מלוטש מדי.",
    source: "Social Media Today",
    category: "platform",
    whyItMatters:
      "חלון הזדמנות לרילס — דווקא עכשיו, ודווקא בלי הפקה כבדה.",
    suggestedAngle:
      "תני לקהל היתר: וידאו 'מספיק טוב' מנצח וידאו מושלם שלא יצא.",
    hotness: 76,
    worthPosting: true,
    recommendedPlatform: "instagram",
    createdAt: "2026-05-22T06:10:00Z",
  },
  {
    id: "news_character",
    rank: 5,
    title: "כלי חדש שומר על דמות ויזואלית עקבית לאורך קמפיין שלם",
    summary:
      "פיצ'ר שמשמר דמות אחידה לאורך סדרת תמונות — פותר את אחד מכאבי הראש הגדולים של יוצרות ויזואל.",
    source: "בלוג מוצר",
    category: "ai-tool",
    whyItMatters:
      "אפשר סוף סוף לבנות פרזנטורית מותג עקבית — שפה ויזואלית, לא תמונות בודדות.",
    suggestedAngle:
      "'הפסיקי לייצר תמונות, תתחילי לייצר דמות' — מצוין לדמו חי בהרצאה.",
    hotness: 70,
    worthPosting: true,
    recommendedPlatform: "instagram",
    createdAt: "2026-05-22T06:18:00Z",
  },
  {
    id: "news_trust_research",
    rank: 6,
    title: "מחקר חדש: שקיפות על שימוש ב-AI מעלה אמון ומכירות",
    summary:
      "סקר רחב מצא ששיתוף גלוי של שימוש ב-AI בתוכן מעלה את אמון הקהל ואת שיעורי ההמרה.",
    source: "מחקר שוק",
    category: "research",
    whyItMatters:
      "נתונים שתומכים בדיוק במסר שלך — שקיפות היא לא סיכון, היא נכס.",
    suggestedAngle:
      "פוסט סמכות מבוסס מספרים: למה הסתרה עולה לך כסף.",
    hotness: 64,
    worthPosting: true,
    recommendedPlatform: "linkedin",
    createdAt: "2026-05-22T06:25:00Z",
  },
];

/* ---------- 5 פוסטים להכין היום ---------- */
export const mockDailyPosts: DailyPost[] = [
  {
    id: "daily_hot",
    kind: "hot-social",
    title: "תגובה מהירה לטרנד מודלי הווידאו",
    whyNow:
      "זה הנושא הכי חם בפיד הבוקר. חלון התגובה הוא 24-48 שעות — אחרי זה זה כבר 'ישן'.",
    platform: "instagram",
    angle: "פרשנות, לא דיווח: 'תקציב הפקה כבר לא תירוץ — אז מה כן?'",
    effort: "30min",
    seedTask: "reels-script",
    seedInput:
      "דור חדש של מודלי וידאו מייצר קליפים שלמים מטקסט — איך לא לאבד טעם כשהכל נהיה זול",
  },
  {
    id: "daily_news",
    kind: "news",
    title: "פוסט מהכותרת: תשלום ישיר ליוצרות תוכן AI",
    whyNow:
      "כותרת מספר 2 הבוקר, וזה בדיוק המסר שאת מובילה כבר שנה. רגע מנצח.",
    platform: "linkedin",
    angle: "'אמרתי שזה מגיע' — שקיפות הפכה מ-nice to have לכסף.",
    effort: "15min",
    seedTask: "news-to-post",
    seedInput: "רשתות חברתיות משיקות תשלום ישיר ליוצרות תוכן AI",
  },
  {
    id: "daily_camera",
    kind: "camera-video",
    title: "סרטון מול מצלמה: 'מפרומפטר למנהל'",
    whyNow:
      "סוכני AI הם הנושא של הרבעון. סרטון דיבור קצר ימצב אותך מוקדם.",
    platform: "linkedin",
    angle: "המיומנות החדשה היא ניהול, לא כתיבה. הסבירי בגובה העיניים.",
    effort: "30min",
    seedTask: "camera-coach",
    seedInput: "מפרומפטר למנהל — המיומנות החדשה של 2026 בעבודה עם AI",
  },
  {
    id: "daily_linkedin",
    kind: "linkedin-facebook",
    title: "פוסט סמכות: 3 טעויות של מותגים עם AI",
    whyNow:
      "הפוסט כמעט מוכן בתיבת הרעיונות. 15 דקות ליטוש — והוא יוצא.",
    platform: "linkedin",
    angle: "ביקורת מדויקת ובונה — ממצב אותך כמומחית, לא עוד קול.",
    effort: "15min",
    seedTask: "linkedin-post",
    seedInput: "3 הטעויות שמותגים עושים עם AI ב-2026 — וכל אחת ניתנת לתיקון",
  },
  {
    id: "daily_community",
    kind: "community",
    title: "פוסט לקהילת הבננות: כלי Google חדש ששווה להכיר",
    whyNow:
      "הקהילה אוהבת טיפים פרקטיים על כלי Google. פוסט קצר שמייצר שיחה.",
    platform: "community",
    angle: "טיפ אחד מעשי + שאלה לקהילה — בלי הרצאה, בגובה העיניים.",
    effort: "15min",
    seedTask: "community-post",
    seedInput:
      "כלי AI חדש בתוך Google Workspace ששווה לכל יוצרת תוכן להכיר השבוע",
  },
];
